[31m[2021-02-09 13:28:53,397] [allapi.py:45] [allapi:getRoleList] [ERROR]- HTTPConnectionPool(host='qaqdi-gw.qdingnet.com', port=80): Max retries exceeded with url: /qdi-sales-online-api/staffRole/getRoleList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10909f730>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))[0m
[32m[2021-02-09 13:30:16,410] [allapi.py:39] [allapi:getRoleList] [INFO]- 获取角色列表数据接口成功{"code": 400102, "message": "\u672a\u767b\u5f55", "success": false, "traceId": "4dd57e83a88c4ca18a657195ff88403c"}[0m
[32m[2021-02-09 13:31:50,733] [allapi.py:39] [allapi:getRoleList] [INFO]- 获取角色列表数据接口成功{"code": 400102, "message": "\u672a\u767b\u5f55", "success": false, "traceId": "2da19224289b419a8af770d6e3a6983a"}[0m
